#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RouTor.Client.Resource", IsApplication=true)]

namespace RouTor.Client
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int cameraBearing = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int cameraTargetLat = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int cameraTargetLng = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int cameraTilt = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int cameraZoom = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int circle_border_color = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int circle_border_width = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int circle_color = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int circle_padding = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int circle_radius = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int circle_radius_pressed = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int layout_box = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int mapType = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int rectLayout = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int roundLayout = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int shadow_width = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int uiCompass = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int uiRotateGestures = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int uiScrollGestures = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int uiTiltGestures = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int uiZoomControls = 2130771988;
			
			// aapt resource value: 0x7F010015
			public const int uiZoomGestures = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int update_interval = 2130771990;
			
			// aapt resource value: 0x7F010017
			public const int useViewLifecycle = 2130771991;
			
			// aapt resource value: 0x7F010018
			public const int zOrderOnTop = 2130771992;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int black = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int blue = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int common_action_bar_splitter = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int common_signin_btn_dark_text_default = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int common_signin_btn_dark_text_disabled = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int common_signin_btn_dark_text_focused = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int common_signin_btn_dark_text_pressed = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int common_signin_btn_default_background = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int common_signin_btn_light_text_default = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int common_signin_btn_light_text_disabled = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int common_signin_btn_light_text_focused = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int common_signin_btn_light_text_pressed = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int common_signin_btn_text_dark = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int common_signin_btn_text_light = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int dark_blue = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int disabled_text_light = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int dismiss_close = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int dismiss_close_pressed = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int dismiss_overlay_bg = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int green = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int grey = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int light_grey = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int orange = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int primary_text_dark = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int primary_text_light = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int red = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int secondary_text_light = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int semitransparent_grey = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int white = 2130837532;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int card_content_padding_rect_left = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int card_content_padding_rect_right = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int card_content_padding_rect_top = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int close_button_diameter = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int dismiss_padding = 2130903044;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public const int card_background = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int card_frame = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int card_frame_pressed = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int close_button = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int common_signin_btn_icon_dark = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int common_signin_btn_icon_disabled_dark = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int common_signin_btn_icon_disabled_focus_dark = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int common_signin_btn_icon_disabled_focus_light = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int common_signin_btn_icon_disabled_light = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int common_signin_btn_icon_focus_dark = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int common_signin_btn_icon_focus_light = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int common_signin_btn_icon_light = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int common_signin_btn_icon_normal_dark = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int common_signin_btn_icon_normal_light = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int common_signin_btn_icon_pressed_dark = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int common_signin_btn_icon_pressed_light = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int common_signin_btn_text_dark = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int common_signin_btn_text_disabled_dark = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int common_signin_btn_text_disabled_focus_dark = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int common_signin_btn_text_disabled_focus_light = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int common_signin_btn_text_disabled_light = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int common_signin_btn_text_focus_dark = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int common_signin_btn_text_focus_light = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int common_signin_btn_text_light = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int common_signin_btn_text_normal_dark = 2130968600;
			
			// aapt resource value: 0x7F040019
			public const int common_signin_btn_text_normal_light = 2130968601;
			
			// aapt resource value: 0x7F04001A
			public const int common_signin_btn_text_pressed_dark = 2130968602;
			
			// aapt resource value: 0x7F04001B
			public const int common_signin_btn_text_pressed_light = 2130968603;
			
			// aapt resource value: 0x7F04001C
			public const int confirmation_animation = 2130968604;
			
			// aapt resource value: 0x7F04001D
			public const int generic_confirmation_00163 = 2130968605;
			
			// aapt resource value: 0x7F04001E
			public const int generic_confirmation_00164 = 2130968606;
			
			// aapt resource value: 0x7F04001F
			public const int generic_confirmation_00165 = 2130968607;
			
			// aapt resource value: 0x7F040020
			public const int generic_confirmation_00166 = 2130968608;
			
			// aapt resource value: 0x7F040021
			public const int generic_confirmation_00167 = 2130968609;
			
			// aapt resource value: 0x7F040022
			public const int generic_confirmation_00168 = 2130968610;
			
			// aapt resource value: 0x7F040023
			public const int generic_confirmation_00169 = 2130968611;
			
			// aapt resource value: 0x7F040024
			public const int generic_confirmation_00170 = 2130968612;
			
			// aapt resource value: 0x7F040025
			public const int generic_confirmation_00171 = 2130968613;
			
			// aapt resource value: 0x7F040026
			public const int generic_confirmation_00172 = 2130968614;
			
			// aapt resource value: 0x7F040027
			public const int generic_confirmation_00173 = 2130968615;
			
			// aapt resource value: 0x7F040028
			public const int generic_confirmation_00174 = 2130968616;
			
			// aapt resource value: 0x7F040029
			public const int generic_confirmation_00175 = 2130968617;
			
			// aapt resource value: 0x7F04002A
			public const int generic_confirmation_00176 = 2130968618;
			
			// aapt resource value: 0x7F04002B
			public const int generic_confirmation_00177 = 2130968619;
			
			// aapt resource value: 0x7F04002C
			public const int generic_confirmation_00178 = 2130968620;
			
			// aapt resource value: 0x7F04002D
			public const int generic_confirmation_00179 = 2130968621;
			
			// aapt resource value: 0x7F04002E
			public const int generic_confirmation_00180 = 2130968622;
			
			// aapt resource value: 0x7F04002F
			public const int generic_confirmation_00181 = 2130968623;
			
			// aapt resource value: 0x7F040030
			public const int generic_confirmation_00182 = 2130968624;
			
			// aapt resource value: 0x7F040031
			public const int generic_confirmation_00183 = 2130968625;
			
			// aapt resource value: 0x7F040032
			public const int generic_confirmation_00184 = 2130968626;
			
			// aapt resource value: 0x7F040033
			public const int generic_confirmation_00185 = 2130968627;
			
			// aapt resource value: 0x7F040034
			public const int generic_confirmation_00186 = 2130968628;
			
			// aapt resource value: 0x7F040035
			public const int generic_confirmation_00187 = 2130968629;
			
			// aapt resource value: 0x7F040036
			public const int generic_confirmation_00188 = 2130968630;
			
			// aapt resource value: 0x7F040037
			public const int generic_confirmation_00189 = 2130968631;
			
			// aapt resource value: 0x7F040038
			public const int generic_confirmation_00190 = 2130968632;
			
			// aapt resource value: 0x7F040039
			public const int generic_confirmation_00191 = 2130968633;
			
			// aapt resource value: 0x7F04003A
			public const int generic_confirmation_00192 = 2130968634;
			
			// aapt resource value: 0x7F04003B
			public const int generic_confirmation_00193 = 2130968635;
			
			// aapt resource value: 0x7F04003C
			public const int go_to_phone_00156 = 2130968636;
			
			// aapt resource value: 0x7F04003D
			public const int go_to_phone_00157 = 2130968637;
			
			// aapt resource value: 0x7F04003E
			public const int go_to_phone_00158 = 2130968638;
			
			// aapt resource value: 0x7F04003F
			public const int go_to_phone_00159 = 2130968639;
			
			// aapt resource value: 0x7F040040
			public const int go_to_phone_00160 = 2130968640;
			
			// aapt resource value: 0x7F040041
			public const int go_to_phone_00161 = 2130968641;
			
			// aapt resource value: 0x7F040042
			public const int go_to_phone_00162 = 2130968642;
			
			// aapt resource value: 0x7F040043
			public const int go_to_phone_00163 = 2130968643;
			
			// aapt resource value: 0x7F040044
			public const int go_to_phone_00164 = 2130968644;
			
			// aapt resource value: 0x7F040045
			public const int go_to_phone_00165 = 2130968645;
			
			// aapt resource value: 0x7F040046
			public const int go_to_phone_00166 = 2130968646;
			
			// aapt resource value: 0x7F040047
			public const int go_to_phone_00167 = 2130968647;
			
			// aapt resource value: 0x7F040048
			public const int go_to_phone_00168 = 2130968648;
			
			// aapt resource value: 0x7F040049
			public const int go_to_phone_00169 = 2130968649;
			
			// aapt resource value: 0x7F04004A
			public const int go_to_phone_00170 = 2130968650;
			
			// aapt resource value: 0x7F04004B
			public const int go_to_phone_00171 = 2130968651;
			
			// aapt resource value: 0x7F04004C
			public const int go_to_phone_00172 = 2130968652;
			
			// aapt resource value: 0x7F04004D
			public const int go_to_phone_00173 = 2130968653;
			
			// aapt resource value: 0x7F04004E
			public const int go_to_phone_00174 = 2130968654;
			
			// aapt resource value: 0x7F04004F
			public const int go_to_phone_00175 = 2130968655;
			
			// aapt resource value: 0x7F040050
			public const int go_to_phone_00176 = 2130968656;
			
			// aapt resource value: 0x7F040051
			public const int go_to_phone_00177 = 2130968657;
			
			// aapt resource value: 0x7F040052
			public const int go_to_phone_00178 = 2130968658;
			
			// aapt resource value: 0x7F040053
			public const int go_to_phone_00185 = 2130968659;
			
			// aapt resource value: 0x7F040054
			public const int go_to_phone_00186 = 2130968660;
			
			// aapt resource value: 0x7F040055
			public const int go_to_phone_00187 = 2130968661;
			
			// aapt resource value: 0x7F040056
			public const int go_to_phone_00188 = 2130968662;
			
			// aapt resource value: 0x7F040057
			public const int go_to_phone_00189 = 2130968663;
			
			// aapt resource value: 0x7F040058
			public const int go_to_phone_00190 = 2130968664;
			
			// aapt resource value: 0x7F040059
			public const int go_to_phone_00191 = 2130968665;
			
			// aapt resource value: 0x7F04005A
			public const int go_to_phone_00192 = 2130968666;
			
			// aapt resource value: 0x7F04005B
			public const int go_to_phone_00193 = 2130968667;
			
			// aapt resource value: 0x7F04005C
			public const int go_to_phone_00194 = 2130968668;
			
			// aapt resource value: 0x7F04005D
			public const int go_to_phone_00195 = 2130968669;
			
			// aapt resource value: 0x7F04005E
			public const int go_to_phone_00196 = 2130968670;
			
			// aapt resource value: 0x7F04005F
			public const int go_to_phone_00197 = 2130968671;
			
			// aapt resource value: 0x7F040060
			public const int go_to_phone_00198 = 2130968672;
			
			// aapt resource value: 0x7F040061
			public const int go_to_phone_00199 = 2130968673;
			
			// aapt resource value: 0x7F040062
			public const int go_to_phone_00200 = 2130968674;
			
			// aapt resource value: 0x7F040063
			public const int go_to_phone_00210 = 2130968675;
			
			// aapt resource value: 0x7F040064
			public const int go_to_phone_00211 = 2130968676;
			
			// aapt resource value: 0x7F040065
			public const int go_to_phone_00212 = 2130968677;
			
			// aapt resource value: 0x7F040066
			public const int go_to_phone_00213 = 2130968678;
			
			// aapt resource value: 0x7F040067
			public const int go_to_phone_00214 = 2130968679;
			
			// aapt resource value: 0x7F040068
			public const int go_to_phone_00215 = 2130968680;
			
			// aapt resource value: 0x7F040069
			public const int go_to_phone_00216 = 2130968681;
			
			// aapt resource value: 0x7F04006A
			public const int go_to_phone_00217 = 2130968682;
			
			// aapt resource value: 0x7F04006B
			public const int go_to_phone_00218 = 2130968683;
			
			// aapt resource value: 0x7F04006C
			public const int go_to_phone_00219 = 2130968684;
			
			// aapt resource value: 0x7F04006D
			public const int go_to_phone_00220 = 2130968685;
			
			// aapt resource value: 0x7F04006E
			public const int go_to_phone_00221 = 2130968686;
			
			// aapt resource value: 0x7F04006F
			public const int go_to_phone_00222 = 2130968687;
			
			// aapt resource value: 0x7F040070
			public const int go_to_phone_00223 = 2130968688;
			
			// aapt resource value: 0x7F040071
			public const int go_to_phone_00224 = 2130968689;
			
			// aapt resource value: 0x7F040072
			public const int go_to_phone_animation = 2130968690;
			
			// aapt resource value: 0x7F040079
			public const int Icon = 2130968697;
			
			// aapt resource value: 0x7F040073
			public const int ic_full_cancel = 2130968691;
			
			// aapt resource value: 0x7F040074
			public const int ic_full_sad = 2130968692;
			
			// aapt resource value: 0x7F040075
			public const int ic_plusone_medium_off_client = 2130968693;
			
			// aapt resource value: 0x7F040076
			public const int ic_plusone_small_off_client = 2130968694;
			
			// aapt resource value: 0x7F040077
			public const int ic_plusone_standard_off_client = 2130968695;
			
			// aapt resource value: 0x7F040078
			public const int ic_plusone_tall_off_client = 2130968696;
			
			// aapt resource value: 0x7F04007A
			public const int powered_by_google_dark = 2130968698;
			
			// aapt resource value: 0x7F04007B
			public const int powered_by_google_light = 2130968699;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050000
			public const int action_error = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int action_success = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int all = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int animation = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int bottom = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int dismiss_overlay_button = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int dismiss_overlay_explain = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int error_message = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int hybrid = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int left = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int message = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int myButton = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int none = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int normal = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int right = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int satellite = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int terrain = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int text = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int title = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int top = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int watch_view_stub = 2131034132;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F070000
			public const int confirmation_activity_layout = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int dismiss_overlay = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int Main = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int RectangleMain = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int RoundMain = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int watch_card_content = 2131165189;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080003
			public const int app_name = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int auth_client_needs_enabling_title = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int auth_client_needs_installation_title = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int auth_client_needs_update_title = 2131230726;
			
			// aapt resource value: 0x7F080007
			public const int auth_client_play_services_err_notification_msg = 2131230727;
			
			// aapt resource value: 0x7F080008
			public const int auth_client_requested_by_msg = 2131230728;
			
			// aapt resource value: 0x7F080009
			public const int auth_client_using_bad_version_title = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public const int common_google_play_services_enable_button = 2131230730;
			
			// aapt resource value: 0x7F08000B
			public const int common_google_play_services_enable_text = 2131230731;
			
			// aapt resource value: 0x7F08000C
			public const int common_google_play_services_enable_title = 2131230732;
			
			// aapt resource value: 0x7F08000D
			public const int common_google_play_services_error_notification_requested_by_msg = 2131230733;
			
			// aapt resource value: 0x7F08000E
			public const int common_google_play_services_install_button = 2131230734;
			
			// aapt resource value: 0x7F08000F
			public const int common_google_play_services_install_text_phone = 2131230735;
			
			// aapt resource value: 0x7F080010
			public const int common_google_play_services_install_text_tablet = 2131230736;
			
			// aapt resource value: 0x7F080011
			public const int common_google_play_services_install_title = 2131230737;
			
			// aapt resource value: 0x7F080012
			public const int common_google_play_services_invalid_account_text = 2131230738;
			
			// aapt resource value: 0x7F080013
			public const int common_google_play_services_invalid_account_title = 2131230739;
			
			// aapt resource value: 0x7F080014
			public const int common_google_play_services_needs_enabling_title = 2131230740;
			
			// aapt resource value: 0x7F080015
			public const int common_google_play_services_network_error_text = 2131230741;
			
			// aapt resource value: 0x7F080016
			public const int common_google_play_services_network_error_title = 2131230742;
			
			// aapt resource value: 0x7F080017
			public const int common_google_play_services_notification_needs_installation_title = 2131230743;
			
			// aapt resource value: 0x7F080018
			public const int common_google_play_services_notification_needs_update_title = 2131230744;
			
			// aapt resource value: 0x7F080019
			public const int common_google_play_services_notification_ticker = 2131230745;
			
			// aapt resource value: 0x7F08001A
			public const int common_google_play_services_unknown_issue = 2131230746;
			
			// aapt resource value: 0x7F08001B
			public const int common_google_play_services_unsupported_date_text = 2131230747;
			
			// aapt resource value: 0x7F08001C
			public const int common_google_play_services_unsupported_text = 2131230748;
			
			// aapt resource value: 0x7F08001D
			public const int common_google_play_services_unsupported_title = 2131230749;
			
			// aapt resource value: 0x7F08001E
			public const int common_google_play_services_update_button = 2131230750;
			
			// aapt resource value: 0x7F08001F
			public const int common_google_play_services_update_text = 2131230751;
			
			// aapt resource value: 0x7F080020
			public const int common_google_play_services_update_title = 2131230752;
			
			// aapt resource value: 0x7F080021
			public const int common_signin_button_text = 2131230753;
			
			// aapt resource value: 0x7F080022
			public const int common_signin_button_text_long = 2131230754;
			
			// aapt resource value: 0x7F080023
			public const int hello_rect = 2131230755;
			
			// aapt resource value: 0x7F080024
			public const int hello_round = 2131230756;
			
			// aapt resource value: 0x7F080000
			public const int LANIP = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int Password = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int Username = 2131230722;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public const int CardContent = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int CardText = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int CardTitle = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int DismissOverlayText = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int TextAppearance_Wearable_Large = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int TextAppearance_Wearable_Medium = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int TextAppearance_Wearable_Small = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int TextView_Large = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int TextView_Large_Light = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int TextView_Medium = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int TextView_Medium_Light = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int TextView_Small = 2131296267;
			
			// aapt resource value: 0x7F09000C
			public const int TextView_Small_Light = 2131296268;
			
			// aapt resource value: 0x7F09000D
			public const int Theme_Wearable = 2131296269;
			
			// aapt resource value: 0x7F09000E
			public const int Theme_Wearable_Modal = 2131296270;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F01000B }
			public static int[] BoxInsetLayout = new int[] {
					2130771979};
			
			// aapt resource value: 0
			public const int BoxInsetLayout_layout_box = 0;
			
			// aapt resource value: { 0x1010119,0x7F010005,0x7F010006,0x7F010007,0x7F010008,0x7F010009,0x7F01000A,0x7F01000F }
			public static int[] CircledImageView = new int[] {
					16843033,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771983};
			
			// aapt resource value: 0
			public const int CircledImageView_android_src = 0;
			
			// aapt resource value: 1
			public const int CircledImageView_circle_border_color = 1;
			
			// aapt resource value: 2
			public const int CircledImageView_circle_border_width = 2;
			
			// aapt resource value: 3
			public const int CircledImageView_circle_color = 3;
			
			// aapt resource value: 4
			public const int CircledImageView_circle_padding = 4;
			
			// aapt resource value: 5
			public const int CircledImageView_circle_radius = 5;
			
			// aapt resource value: 6
			public const int CircledImageView_circle_radius_pressed = 6;
			
			// aapt resource value: 7
			public const int CircledImageView_shadow_width = 7;
			
			// aapt resource value: { 0x7F010016 }
			public static int[] DelayedConfirmationView = new int[] {
					2130771990};
			
			// aapt resource value: 0
			public const int DelayedConfirmationView_update_interval = 0;
			
			// aapt resource value: { 0x7F010000,0x7F010001,0x7F010002,0x7F010003,0x7F010004,0x7F01000C,0x7F010010,0x7F010011,0x7F010012,0x7F010013,0x7F010014,0x7F010015,0x7F010017,0x7F010018 }
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771980,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771991,
					2130771992};
			
			// aapt resource value: 0
			public const int MapAttrs_cameraBearing = 0;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraTargetLat = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLng = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTilt = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraZoom = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_mapType = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_uiCompass = 6;
			
			// aapt resource value: 7
			public const int MapAttrs_uiRotateGestures = 7;
			
			// aapt resource value: 8
			public const int MapAttrs_uiScrollGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiTiltGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiZoomControls = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomGestures = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_useViewLifecycle = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_zOrderOnTop = 13;
			
			// aapt resource value: { 0x7F01000D,0x7F01000E }
			public static int[] WatchViewStub = new int[] {
					2130771981,
					2130771982};
			
			// aapt resource value: 0
			public const int WatchViewStub_rectLayout = 0;
			
			// aapt resource value: 1
			public const int WatchViewStub_roundLayout = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
